### ISSUE TITLE
temp access key

### ISSUE THREAD

**Issue by wbdsnx** [natml-hub/BlazePose#2]
Can you provide a temporary access key to let us verify the correctness of the function? If we meet our expectations, we can apply to the authorities for new ones, 714658630@qq.com This is my mailbox. Look forward to your reply, thank you

**Comment by olokobayusuf** [comment]
Hey @wbdsnx , NatML Hub is free to use, so you can fetch ML models without any subscription. And NatDevice, which this example project uses for streaming the camera, [can now be used as a free trial](https://docs.natml.ai/natdevice/prelims/faq). Simply open an account on [NatML Hub](https://hub.natml.ai) by signing in, then get an access key from your [profile page](https://hub.natml.ai/profile). Let me know if you face any issues.

**Comment by wbdsnx** [comment]
@olokobayusuf  I have got an access key , but I still encounter this problem "InvalidOperationException: NatDevice app token is invalid. Check your NatML access key and plan." with " cameraDevice.StartRunning(previewTextureOutput);" 
I don't know what I should do?
![image](https://user-images.githubusercontent.com/45476463/199878899-f2a6d79d-e359-4b63-a803-1a3df7b8f7d6.png)

**Comment by xuyixun21** [comment]
+1

**Comment by olokobayusuf** [comment]
@wbdsnx @xuyixun21 I just updated the dependencies of the project to the latest version of NatDevice which has the free trial tier. Try it out now.
